# Dependency-free bundler for machines without Node.
#
# Concatenates every CommonJS module under src/ into a single file with a tiny
# require shim. `npm run build` (frida-compile) consumes the same sources and
# produces a smaller bundle; use that once Node is installed.
#
#   powershell -ExecutionPolicy Bypass -File tools\bundle.ps1

$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot
$srcDir = Join-Path $root 'src'
$outFile = Join-Path $root 'dist\aerox-tas.js'

New-Item -ItemType Directory -Force -Path (Split-Path -Parent $outFile) | Out-Null

$assetsDir = Join-Path $root 'assets\skins'
$defaultsFile = Join-Path $srcDir 'tas\skin-defaults.js'
$skinFiles = @()
if (Test-Path $assetsDir) {
    $skinFiles = @(Get-ChildItem -Path $assetsDir -File | Where-Object {
        $_.Extension -match '\.(png|jpg|jpeg)$' -and $_.Name -notmatch '^[_]' -and $_.BaseName -notmatch '\d$'
    })
}
if ($skinFiles.Count -gt 0) {
    $def = [System.Text.StringBuilder]::new()
    [void]$def.AppendLine('// Generated by tools/bundle.ps1 from assets/skins. Do not edit.')
    [void]$def.AppendLine('module.exports = {')
    $skinFiles | Sort-Object Name | ForEach-Object {
        $b64 = [Convert]::ToBase64String([IO.File]::ReadAllBytes($_.FullName))
        [void]$def.AppendLine(('    {0}: ''{1}'',' -f (ConvertTo-Json $_.BaseName), $b64))
        Write-Host ("embed {0}" -f $_.Name)
    }
    [void]$def.AppendLine('};')
    [IO.File]::WriteAllText($defaultsFile, $def.ToString())
} else {
    Write-Host 'assets/skins empty - keeping existing src/tas/skin-defaults.js'
}

$sb = [System.Text.StringBuilder]::new()

[void]$sb.AppendLine('// Generated by tools/bundle.ps1 - do not edit. Edit src/ instead.')
[void]$sb.AppendLine('(function () {')
[void]$sb.AppendLine('  "use strict";')
[void]$sb.AppendLine('  var __defs = {};')
[void]$sb.AppendLine('  var __cache = {};')
[void]$sb.AppendLine('  function __resolve(from, path) {')
[void]$sb.AppendLine('    if (path.charAt(0) !== ".") return path;')
[void]$sb.AppendLine('    var base = from.split("/"); base.pop();')
[void]$sb.AppendLine('    var parts = path.split("/");')
[void]$sb.AppendLine('    for (var i = 0; i < parts.length; i++) {')
[void]$sb.AppendLine('      if (parts[i] === "." || parts[i] === "") continue;')
[void]$sb.AppendLine('      if (parts[i] === "..") base.pop(); else base.push(parts[i]);')
[void]$sb.AppendLine('    }')
[void]$sb.AppendLine('    return base.join("/");')
[void]$sb.AppendLine('  }')
[void]$sb.AppendLine('  function __require(id) {')
[void]$sb.AppendLine('    if (__cache[id]) return __cache[id].exports;')
[void]$sb.AppendLine('    var def = __defs[id];')
[void]$sb.AppendLine('    if (!def) throw new Error("module not found: " + id);')
[void]$sb.AppendLine('    var m = { exports: {} };')
[void]$sb.AppendLine('    __cache[id] = m;')
[void]$sb.AppendLine('    def(m, m.exports, function (p) { return __require(__resolve(id, p)); });')
[void]$sb.AppendLine('    return m.exports;')
[void]$sb.AppendLine('  }')

Get-ChildItem -Path $srcDir -Recurse -Filter *.js | Sort-Object FullName | ForEach-Object {
    $id = $_.FullName.Substring($srcDir.Length + 1) -replace '\\', '/' -replace '\.js$', ''
    [void]$sb.AppendLine("  __defs[" + (ConvertTo-Json $id) + "] = function (module, exports, require) {")
    [void]$sb.AppendLine([IO.File]::ReadAllText($_.FullName, [Text.Encoding]::UTF8))
    [void]$sb.AppendLine('  };')
}

[void]$sb.AppendLine('  __require("boot");')
[void]$sb.AppendLine('})();')

$utf8 = New-Object System.Text.UTF8Encoding $false
[IO.File]::WriteAllText($outFile, $sb.ToString(), $utf8)
Write-Host "bundled -> $outFile"
