"""Cross-platform bundler (macOS, Linux, Windows) - same output as bundle.ps1.

    python3 tools/bundle.py

1. Bakes assets/skins/*.png|jpg|jpeg into src/tas/skin-defaults.js (base64).
   Skipped files: names starting with "_" and names ending in a digit.
2. Wraps every module under src/ in a tiny CommonJS shim and writes
   dist/aerox-tas.js. The entry point is src/boot.js.

Needs only the Python 3 standard library.
"""

import base64
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'src')
OUT = os.path.join(ROOT, 'dist', 'aerox-tas.js')
SKINS = os.path.join(ROOT, 'assets', 'skins')
DEFAULTS = os.path.join(SRC, 'tas', 'skin-defaults.js')

SHIM_HEAD = '''// Generated by tools/bundle.py - do not edit. Edit src/ instead.
(function () {
  "use strict";
  var __defs = {};
  var __cache = {};
  function __resolve(from, path) {
    if (path.charAt(0) !== ".") return path;
    var base = from.split("/"); base.pop();
    var parts = path.split("/");
    for (var i = 0; i < parts.length; i++) {
      if (parts[i] === "." || parts[i] === "") continue;
      if (parts[i] === "..") base.pop(); else base.push(parts[i]);
    }
    return base.join("/");
  }
  function __require(id) {
    if (__cache[id]) return __cache[id].exports;
    if (!__defs[id] && __defs[id + "/index"]) id = id + "/index";
    if (__cache[id]) return __cache[id].exports;
    var def = __defs[id];
    if (!def) throw new Error("module not found: " + id);
    var m = { exports: {} };
    __cache[id] = m;
    def(m, m.exports, function (p) { return __require(__resolve(id, p)); });
    return m.exports;
  }
'''
SHIM_TAIL = '''  __require("boot");
})();
'''


def bake_skins():
    if not os.path.isdir(SKINS):
        print('assets/skins missing - keeping existing src/tas/skin-defaults.js')
        return
    files = []
    for name in os.listdir(SKINS):
        base, ext = os.path.splitext(name)
        if ext.lower() not in ('.png', '.jpg', '.jpeg'):
            continue
        if name.startswith('_') or base[-1:].isdigit():
            continue
        files.append(name)
    if not files:
        print('assets/skins empty - keeping existing src/tas/skin-defaults.js')
        return
    lines = ['// Generated by tools/bundle.py from assets/skins. Do not edit.', 'module.exports = {']
    for name in sorted(files, key=str.lower):
        data = open(os.path.join(SKINS, name), 'rb').read()
        b64 = base64.b64encode(data).decode('ascii')
        lines.append(f"    {json.dumps(os.path.splitext(name)[0])}: '{b64}',")
        print('embed', name)
    lines.append('};')
    with open(DEFAULTS, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(lines) + '\n')


def modules():
    found = []
    for dirpath, _dirs, names in os.walk(SRC):
        for name in names:
            if name.endswith('.js'):
                full = os.path.join(dirpath, name)
                found.append(full)
    return sorted(found, key=lambda p: p.lower())


def main():
    bake_skins()
    parts = [SHIM_HEAD]
    for full in modules():
        mod_id = os.path.relpath(full, SRC).replace(os.sep, '/')[:-3]
        parts.append(f'  __defs[{json.dumps(mod_id)}] = function (module, exports, require) {{\n')
        with open(full, encoding='utf-8') as f:
            parts.append(f.read().rstrip('\n') + '\n')
        parts.append('  };\n')
    parts.append(SHIM_TAIL)
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write(''.join(parts))
    print('bundled ->', OUT)


if __name__ == '__main__':
    main()
